### ISSUE TITLE
Create an initial script to scrape data from Zenodo

### ISSUE THREAD

**Issue by dgarijo** [STEELISI/CKIDS#2]
Explore Zenodo's API or beautiful soup to extract concepts relevant to a keyword (or by number)

**Comment by dgarijo** [comment]
@hardiksurana,
thanks for working on this. I cannot review this issue, because:
- There is no indication on how to execute the script.
- There is no definition on what the script does or how to configure.
- There is no documentation or examples (I see results, but this is for me to interpret).

I know I am being picky, but these are good practices for software engineering:
- Add a readme file explaining what are these scripts
- In the readme file, add instructions on how to invoke scripts and if there are parameters or assumptions.
- Show how to use the script with an example
- Explain what is the expected result.

Thanks!

**Comment by hardiksurana** [comment]
@dgarijo, thank you for the informative points. I have made the necessary changes and pushed them. Kindly review the same.

**Comment by dgarijo** [comment]
Excellent, will try the scripts ASAP. I will close the issue, as the doc is there now.
